name: Projekt
on: push
jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install scipy pint open_atmos_jupyter_utils matplotlib numpy
      - uses: actions/checkout@v4
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert ipykernel
      #- run: python -m nbconvert --to pdf --execute mpdata_2d_numpy_only.ipynb
      - uses: actions/upload-artifact@v4
        with: 
          path: |
            MUP_Projekt_Jan_Szwedo_Sprawozdanie.pdf
            MUP_Projekt_Jan_Szwedo.ipynb
            eksponencjalna_N_2.gif
            tangens_N_3.gif
            tsunami_tangens_N_3.svg
            tsunami_eksponencjalna_N_2.svg
            tsunami_liniowa_N_1.svg
            
