name: Projekt
on: push
jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install scipy pint open_atmos_jupyter_utils matplotlib numpy
      - uses: actions/checkout@v4
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert ipykernel
      #- run: python -m nbconvert --to pdf --execute mpdata_2d_numpy_only.ipynb
      - uses: actions/upload-artifact@v4
        with: 
          path: |
            Jan_Szwedo_Projekt_MUP_Sprawozdanie.pdf
            Jan_Szwedo_MUP_Projekt.ipynb
            liniowa_N_1_anim.gif
            eksponencjalna_N_2_anim.gif
            tangens_N_3_anim.gif
            h_od_dx_dla_różnego_N.png
            h_od_dt_dla_różnego_N.png
            tsunami_N_1_21_dt_0.08_dx_5.0.png
            tsunami_N_2_40_dt_0.08_dx_5.0.png
            tsunami_N_3_45_dt_0.08_dx_5.0.png
            h_od_dx_dla_różnego_N.svg
            h_od_dt_dla_różnego_N.svg
            tsunami_N_1_21_dt_0.08_dx_5.0.svg
            tsunami_N_2_40_dt_0.08_dx_5.0.svg
            tsunami_N_3_45_dt_0.08_dx_5.0.svg
            

            
