name: sprawozdanie
on: push
jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install scipy pint open_atmos_jupyter_utils matplotlib numpy
      - uses: actions/checkout@v4
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert
      #- run: puthon -m nbconvert --to pdf --execute mpdata_2d_numpy_only.ipynb
      - run: puthon -m nbconvert -execute mpdata_2d_numpy_only.ipynb
      - uses: actions/upload-artifact@v4
        with: 
          path: anim.gif
